from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(345, 495)
        MainWindow.setMinimumSize(QtCore.QSize(345, 495))
        MainWindow.setMaximumSize(QtCore.QSize(345, 495))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(10, 10, 331, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setAutoFillBackground(False)
        self.result.setStyleSheet("background-color:white")
        self.result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result.setObjectName("result")
        self.sevenBtn = QtWidgets.QPushButton(self.centralwidget)
        self.sevenBtn.setGeometry(QtCore.QRect(10, 200, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.sevenBtn.setFont(font)
        self.sevenBtn.setObjectName("sevenBtn")
        self.eightBtn = QtWidgets.QPushButton(self.centralwidget)
        self.eightBtn.setGeometry(QtCore.QRect(90, 200, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.eightBtn.setFont(font)
        self.eightBtn.setObjectName("eightBtn")
        self.nineBtn = QtWidgets.QPushButton(self.centralwidget)
        self.nineBtn.setGeometry(QtCore.QRect(170, 200, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.nineBtn.setFont(font)
        self.nineBtn.setObjectName("nineBtn")
        self.sixBtn = QtWidgets.QPushButton(self.centralwidget)
        self.sixBtn.setGeometry(QtCore.QRect(170, 270, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.sixBtn.setFont(font)
        self.sixBtn.setObjectName("sixBtn")
        self.fiveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.fiveBtn.setGeometry(QtCore.QRect(90, 270, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.fiveBtn.setFont(font)
        self.fiveBtn.setObjectName("fiveBtn")
        self.fourBtn = QtWidgets.QPushButton(self.centralwidget)
        self.fourBtn.setGeometry(QtCore.QRect(10, 270, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.fourBtn.setFont(font)
        self.fourBtn.setObjectName("fourBtn")
        self.threeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.threeBtn.setGeometry(QtCore.QRect(170, 340, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.threeBtn.setFont(font)
        self.threeBtn.setObjectName("threeBtn")
        self.oneBtn = QtWidgets.QPushButton(self.centralwidget)
        self.oneBtn.setGeometry(QtCore.QRect(10, 340, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.oneBtn.setFont(font)
        self.oneBtn.setObjectName("oneBtn")
        self.twoBtn = QtWidgets.QPushButton(self.centralwidget)
        self.twoBtn.setGeometry(QtCore.QRect(90, 340, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.twoBtn.setFont(font)
        self.twoBtn.setObjectName("twoBtn")
        self.pointBtn = QtWidgets.QPushButton(self.centralwidget)
        self.pointBtn.setGeometry(QtCore.QRect(170, 410, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pointBtn.setFont(font)
        self.pointBtn.setObjectName("pointBtn")
        self.zeroBtn = QtWidgets.QPushButton(self.centralwidget)
        self.zeroBtn.setGeometry(QtCore.QRect(90, 410, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.zeroBtn.setFont(font)
        self.zeroBtn.setObjectName("zeroBtn")
        self.negBtn = QtWidgets.QPushButton(self.centralwidget)
        self.negBtn.setGeometry(QtCore.QRect(10, 410, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.negBtn.setFont(font)
        self.negBtn.setObjectName("negBtn")
        self.equalBtn = QtWidgets.QPushButton(self.centralwidget)
        self.equalBtn.setGeometry(QtCore.QRect(270, 410, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.equalBtn.setFont(font)
        self.equalBtn.setObjectName("equalBtn")
        self.subBtn = QtWidgets.QPushButton(self.centralwidget)
        self.subBtn.setGeometry(QtCore.QRect(270, 200, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.subBtn.setFont(font)
        self.subBtn.setObjectName("subBtn")
        self.mulBtn = QtWidgets.QPushButton(self.centralwidget)
        self.mulBtn.setGeometry(QtCore.QRect(270, 270, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.mulBtn.setFont(font)
        self.mulBtn.setObjectName("mulBtn")
        self.divBtn = QtWidgets.QPushButton(self.centralwidget)
        self.divBtn.setGeometry(QtCore.QRect(270, 340, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.divBtn.setFont(font)
        self.divBtn.setObjectName("divBtn")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(250, 130, 16, 351))
        self.frame.setStyleSheet("background-color:#E1E1E1")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.addBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addBtn.setGeometry(QtCore.QRect(270, 130, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.addBtn.setFont(font)
        self.addBtn.setObjectName("addBtn")
        self.clearBtn = QtWidgets.QPushButton(self.centralwidget)
        self.clearBtn.setGeometry(QtCore.QRect(90, 130, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.clearBtn.setFont(font)
        self.clearBtn.setObjectName("clearBtn")
        self.backBtn = QtWidgets.QPushButton(self.centralwidget)
        self.backBtn.setGeometry(QtCore.QRect(170, 130, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.backBtn.setFont(font)
        self.backBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons8-clear-symbol-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backBtn.setIcon(icon)
        self.backBtn.setIconSize(QtCore.QSize(40, 43))
        self.backBtn.setObjectName("backBtn")
        self.factBtn = QtWidgets.QPushButton(self.centralwidget)
        self.factBtn.setGeometry(QtCore.QRect(10, 130, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.factBtn.setFont(font)
        self.factBtn.setObjectName("factBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.result.setText(_translate("MainWindow", "0"))
        self.sevenBtn.setText(_translate("MainWindow", "7"))
        self.eightBtn.setText(_translate("MainWindow", "8"))
        self.nineBtn.setText(_translate("MainWindow", "9"))
        self.sixBtn.setText(_translate("MainWindow", "6"))
        self.fiveBtn.setText(_translate("MainWindow", "5"))
        self.fourBtn.setText(_translate("MainWindow", "4"))
        self.threeBtn.setText(_translate("MainWindow", "3"))
        self.oneBtn.setText(_translate("MainWindow", "1"))
        self.twoBtn.setText(_translate("MainWindow", "2"))
        self.pointBtn.setText(_translate("MainWindow", "."))
        self.zeroBtn.setText(_translate("MainWindow", "0"))
        self.negBtn.setText(_translate("MainWindow", "+/-"))
        self.equalBtn.setText(_translate("MainWindow", "="))
        self.subBtn.setText(_translate("MainWindow", "-"))
        self.mulBtn.setText(_translate("MainWindow", "x"))
        self.divBtn.setText(_translate("MainWindow", "/"))
        self.addBtn.setText(_translate("MainWindow", "+"))
        self.clearBtn.setText(_translate("MainWindow", "C"))
        self.factBtn.setText(_translate("MainWindow", "!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
